name: Update License Year

on:
  schedule:
    - cron: '0 0 1 1 *'  # Runs at midnight on January 1st every year
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-year:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Update LICENSE.md year
      run: |
        python -c "
        from datetime import datetime
        current_year = datetime.now().year
        with open('LICENSE.md', 'r') as file:
            lines = file.readlines()
        with open('LICENSE.md', 'w') as file:
            for line in lines:
                if line.startswith('Copyright (c)'):
                    file.write(f'Copyright (c) {current_year} [Hunter Case]\\n')
                else:
                    file.write(line)
        "

    - name: Commit changes
      run: |
        git config --local user.name 'github-actions'
        git config --local user.email 'github-actions@github.com'
        git add LICENSE.md
        git commit -m 'Update LICENSE year'

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} 